### ISSUE TITLE
animation deadlocks sometimes

### ISSUE THREAD

**Issue by KingDuckZ** [cnjinhao/nana#530]
I don't think this is the same problem I once reported in issue #335, but sorry if this is a duplicate.
When I instantiate my class sometimes the program freezes. In gdb I get this backtrace:

```
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:103
#1  0x00007ffff75c0334 in __GI___pthread_mutex_lock (mutex=0x555555a56e90) at ../nptl/pthread_mutex_lock.c:80
#2  0x00005555555e1caa in __gthread_mutex_lock (__mutex=0x555555a56e90) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/x86_64-pc-linux-gnu/bits/gthr-default.h:748
#3  0x00005555555e40e6 in std::mutex::lock (this=0x555555a56e90) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_mutex.h:103
#4  0x00005555555e52d8 in std::lock_guard<std::mutex>::lock_guard (this=0x7fffffffcb60, __m=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_mutex.h:162
#5  0x00005555555e2176 in nana::animation::performance_manager::insert (this=0x555555a69400, p=0x555555a6edb0) at /home/michele/dev/thirdparty/nana/source/gui/animation.cpp:440
#6  0x00005555555e4d07 in nana::animation::impl::impl (this=0x555555a6edb0, fps=23) at /home/michele/dev/thirdparty/nana/source/gui/animation.cpp:387
#7  0x00005555555e2949 in nana::animation::animation (this=0x7fffffffcd60, fps=23) at /home/michele/dev/thirdparty/nana/source/gui/animation.cpp:565
#8  0x00005555555921b2 in duck::AnimationWithSize::AnimationWithSize (this=0x7fffffffcd60, sz=..., fps=23) at ../../../code/cpp/memoserv/src/gui/animation_with_size.cpp:23
#9  0x0000555555591970 in duck::make_nana_animation (block=..., width=48, height=48, fps=3) at ../../../code/cpp/memoserv/src/gui/make_nana_animation.cpp:33
#10 0x00005555555d742b in duck::MainWindow::open_file_from_dialog (this=0x7fffffffd4a0) at ../../../code/cpp/memoserv/src/gui/main_window.cpp:60
#11 0x00005555555d6af7 in duck::MainWindow::<lambda(nana::menu::item_proxy&)>::operator()(nana::menu::item_proxy &) const (__closure=0x5555559e9218)
    at ../../../code/cpp/memoserv/src/gui/main_window.cpp:30
#12 0x00005555555d7915 in std::_Function_handler<void(nana::drawerbase::menu::menu_item_type::item_proxy&), duck::MainWindow::init_menu()::<lambda(nana::menu::item_proxy&)> >::_M_invoke(const std::_Any_data &, nana::drawerbase::menu::menu_item_type::item_proxy &) (__functor=..., __args#0=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:297
#13 0x0000555555711907 in std::function<void (nana::drawerbase::menu::menu_item_type::item_proxy&)>::operator()(nana::drawerbase::menu::menu_item_type::item_proxy&) const (
    this=0x5555559e9218, __args#0=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:687
#14 0x00005555557109c7 in nana::drawerbase::menu::menu_window::pick (this=0x555555a53b80) at /home/michele/dev/thirdparty/nana/source/gui/widgets/menu.cpp:954
#15 0x000055555571028b in nana::drawerbase::menu::menu_window::popup(bool)::{lambda(nana::arg_mouse const&)#3}::operator()(nana::arg_mouse const&) const (__closure=0x555555a64a18, arg=...)
    at /home/michele/dev/thirdparty/nana/source/gui/widgets/menu.cpp:817
#16 0x0000555555714e32 in std::_Function_handler<void (nana::arg_mouse const&), nana::drawerbase::menu::menu_window::popup(bool)::{lambda(nana::arg_mouse const&)#3}>::_M_invoke(std::_Any_data const&, nana::arg_mouse const&) (__functor=..., __args#0=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:297
#17 0x00005555556641e9 in std::function<void (nana::arg_mouse const&)>::operator()(nana::arg_mouse const&) const (this=0x555555a64a18, __args#0=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:687
#18 0x0000555555662b5c in nana::basic_event<nana::arg_mouse>::emit (this=0x555555a4fb78, arg=..., window_handle=0x555555a60cd0)
    at /home/michele/dev/thirdparty/nana/include/nana/gui/detail/general_events.hpp:233
#19 0x0000555555668617 in nana::detail::window_proc_for_xevent (xevent=...) at /home/michele/dev/thirdparty/nana/source/gui/detail/bedrock_posix.cpp:789
#20 0x0000555555666b30 in nana::detail::window_proc_dispatcher (display=0x5555559b3ee0, msg=...) at /home/michele/dev/thirdparty/nana/source/gui/detail/bedrock_posix.cpp:346
#21 0x00005555557cd8c0 in nana::detail::msg_dispatcher::dispatch (this=0x5555559aa0d0, modal=0) at /home/michele/dev/thirdparty/nana/source/detail/posix/msg_dispatcher.hpp:170
#22 0x00005555557cad04 in nana::detail::platform_spec::msg_dispatch (this=0x5555559938a0 <nana::detail::platform_spec::instance()::object>, modal=0x0)
    at /home/michele/dev/thirdparty/nana/source/detail/platform_spec_posix.cpp:1036
#23 0x000055555566a0fe in nana::detail::bedrock::pump_event (this=0x5555559935c0 <nana::detail::bedrock::bedrock_object>, condition_wd=0x0, is_modal=false)
    at /home/michele/dev/thirdparty/nana/source/gui/detail/bedrock_posix.cpp:1255
#24 0x000055555565e01b in nana::exec () at /home/michele/dev/thirdparty/nana/source/gui/wvl.cpp:102
#25 0x00005555555d674b in duck::run_gui (icon_size=48, icon_fps=3) at ../../../code/cpp/memoserv/src/gui/run_gui.cpp:10
#26 0x000055555558da59 in main (argc=1, argv=0x7fffffffd6d8) at ../../../code/cpp/memoserv/src/gui/main.cpp:38
```

Please ask for any specific detail you may need. My code is open source so I can link to it if necessary.

**Comment by cnjinhao** [comment]
Thank you for reporting this bug.
